version: '3.8'

services:
  db:
    # Version de postgre
    image: postgres:15-alpine
    # Nombre del contenedor, tambien puede ser variable de entorno
    container_name: wazuhAgentDb
    restart: always
    environment:
      # Cambiar a variables de entorno establecidas en jenkins
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
      POSTGRES_DB: ${DB_NAME:-wazuhagentdb}
    # Cambiar a puerto como variable de entorno que se necesite
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      # Correr el script the inicializacion. Si esta en otro lugar, cambiar por el path
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # Guardar la informacion de la base de datos como persistencia
      - db_data:/var/lib/postgresql/data

    # Healthcheck para que se asegure que este corriendo, antes de seguir con el docker compose (la aplicacion como tal)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-wazuhagentdb}"]
      interval: 5s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - db
  # Seccion donde ira el servicio de java
  app:
    image: wazuh-export-agent:latest
    container_name: wazuh-export-agent
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - ./config.txt:/app/config.txt
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5433}
      DB_NAME: ${DB_NAME:-wazuhagentdb}
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-1234}

volumes:
  db_data:      
