-- Crear tabla
-- CAMBIAR POR NOMBRES DE COLUMNAS Y TABLAS USADAS EN BACKEND

CREATE TABLE IF NOT EXISTS agent_severity(
    id BIGSERIAL PRIMARY KEY,
    agent_name VARCHAR(255) NOT NULL,
    agent_ip VARCHAR(255) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    quantity INTEGER NOT NULL,
    date TIMESTAMP NOT NULL
);
