-- Crear tabla
-- CAMBIAR POR NOMBRES DE COLUMNAS Y TABLAS USADAS EN BACKEND

CREATE TABLE IF NOT EXISTS vulnerabilities(
    id BIGSERIAL PRIMARY KEY,
    os_name VARCHAR(255) NOT NULL,
    agent_name VARCHAR(255) NOT NULL,
    vulnerability_id VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    severity VARCHAR(50) NOT NULL
);
