-- Crear tabla
-- CAMBIAR POR NOMBRES DE COLUMNAS Y TABLAS USADAS EN BACKEND

CREATE TABLE IF NOT EXISTS agents(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ip VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS vulnerabilities(
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  serverity INT(32) NOT NULL,
)

CREATE TABLE IF NOT EXISTS vulnerability_status(
  id BIGSERIAL PRIMARY KEY,
  agent BIGINT,
  vulnerability BIGINT,
  FOREIGN KEY (agent) REFERENCES agents(id)
  FOREIGN KEY (vulnerability) REFERENCES vulnerabilities(id)
)
